spring.application.name=hospital-management

# ===== DataSource =====
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===== Multipart Upload (NFR: max 10MB) =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===== JWT Configuration =====
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ===== Logging =====
logging.level.com.example.hospitalmanagement=DEBUG
logging.level.org.springframework.security=INFO

cloudinary.cloud-name=dbh9eggj2
cloudinary.api-key=926281127192243
cloudinary.api-secret=u0MOtYTH8Vj1MXIybKxixvcqlOo
